namespace :db do
  namespace :seed  do
    desc "Dump records from the database into db/seeds.rb"
    task :dump => :environment do

      SeedDump::Perform::run(ENV)

<<<<<<< HEAD
=======
      models = opts['models'].split(',').collect {|x| x.underscore.singularize }

      new_line = "\n"
      puts "Appending seeds to #{opts['file']}." if opts['append']

      seed_rb = ""
      Dir['app/models/*.rb'].sort.each do |f|
	      model_name  = File.basename(f, '.*')
        if models.include?(model_name) || models.empty? 

          puts "Adding #{model_name.camelize} seeds."

      	  create_hash = ""

      	  model = model_name.camelize.constantize
      	  arr = []
      	  arr = model.find(:all, ar_options) unless opts['no-data']
      	  arr = arr.empty? ? [model.new] : arr
      	  arr.each_with_index { |r,i| 

            attr_s = [];

            id_set_string = ''
            r.attributes.each { |k,v|
	      v = r.attribute_for_inspect(k)
              if k == 'id' && opts['with_id']
                id_set_string = "{ |c| c.#{k} = #{v} }.save"
              else
                attr_s.push("#{k.to_sym.inspect} => #{v}") unless k == 'id' && !opts['with_id']
              end 
            }
            create_hash << (i > 0 ? "#{new_line}" : new_line) << "#{model_name.camelize}.create" << '( ' << attr_s.join(', ') << ' )' << id_set_string
          } 
          seed_rb << "#{create_hash}#{new_line}#{new_line}"
        end
      end

      File.open(opts['file'], (opts['append'] ? "a" : "w")) { |f|

      puts "Writing #{opts['file']}."

      unless opts['append']
          cont =<<HERE
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs
HERE
          f << cont
        end

	cont =<<HERE
#{seed_rb}
HERE
      f << cont

      puts "Done."

}
>>>>>>> 0a16825553f5745b0511585ee8bf8cbcfaa4cc93
    end
  end
end
