# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: seed_dump 3.4.0 ruby lib

Gem::Specification.new do |s|
  s.name = "seed_dump".freeze
  s.version = "3.4.0".freeze

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Rob Halff".freeze, "Ryan Oblak".freeze]
  s.date = "1980-01-02"
  s.description = "Dump (parts) of your database to db/seeds.rb to get a headstart creating a meaningful seeds.rb file".freeze
  s.email = "rroblak@gmail.com".freeze
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".github/workflows/release.yml",
    ".rspec",
    "Appraisals",
    "Gemfile",
    "MIT-LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "find_ruby_compat.sh",
    "gemfiles/rails_6.1.gemfile",
    "gemfiles/rails_6.1.gemfile.lock",
    "gemfiles/rails_7.0.gemfile",
    "gemfiles/rails_7.0.gemfile.lock",
    "gemfiles/rails_7.1.gemfile",
    "gemfiles/rails_7.1.gemfile.lock",
    "gemfiles/rails_7.2.gemfile",
    "gemfiles/rails_7.2.gemfile.lock",
    "gemfiles/rails_8.0.gemfile",
    "gemfiles/rails_8.0.gemfile.lock",
    "lib/seed_dump.rb",
    "lib/seed_dump/dump_methods.rb",
    "lib/seed_dump/dump_methods/enumeration.rb",
    "lib/seed_dump/environment.rb",
    "lib/seed_dump/railtie.rb",
    "lib/tasks/seed_dump.rake",
    "seed_dump.gemspec",
    "spec/dump_methods_spec.rb",
    "spec/environment_spec.rb",
    "spec/factories/another_samples.rb",
    "spec/factories/authors.rb",
    "spec/factories/base_users.rb",
    "spec/factories/books.rb",
    "spec/factories/bosses.rb",
    "spec/factories/reviews.rb",
    "spec/factories/samples.rb",
    "spec/factories/yet_another_samples.rb",
    "spec/helpers.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://github.com/rroblak/seed_dump".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.6.9".freeze
  s.summary = "{Seed Dumper for Rails}".freeze

  s.specification_version = 4

  s.add_runtime_dependency(%q<activesupport>.freeze, [">= 4".freeze])
  s.add_runtime_dependency(%q<activerecord>.freeze, [">= 4".freeze])
  s.add_runtime_dependency(%q<seed_dump>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<byebug>.freeze, ["~> 11.1".freeze])
  s.add_development_dependency(%q<factory_bot>.freeze, ["~> 6.1".freeze])
  s.add_development_dependency(%q<activerecord-import>.freeze, ["~> 0.28".freeze])
  s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3".freeze])
end

