# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{seed_dump}
  s.version = "0.3.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rob Halff"]
  s.date = %q{2011-07-14}
  s.description = %q{Dump (parts) of your database to db/seeds.rb to get a headstart creating a meaningful seeds.rb file}
  s.email = %q{rob.halff@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG.rdoc",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "contents.yml",
    "lib/seed_dump.rb",
    "lib/seed_dump/perform.rb",
    "lib/seed_dump/railtie.rb",
    "lib/tasks/seed_dump.rake",
    "seed_dump.gemspec",
    "test/fixtures/samples.yml",
    "test/seed_dump_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/rhalff/seed_dump}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{{Seed Dumper for Rails}}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

